-- ===================== CATEGORIES =====================
INSERT INTO category (name) VALUES ('Fiction');
INSERT INTO category (name) VALUES ('Science Fiction');
INSERT INTO category (name) VALUES ('Fantasy');
INSERT INTO category (name) VALUES ('Mystery');
INSERT INTO category (name) VALUES ('Romance');
INSERT INTO category (name) VALUES ('History');
INSERT INTO category (name) VALUES ('Biography');
INSERT INTO category (name) VALUES ('Self-Help');
INSERT INTO category (name) VALUES ('Science');
INSERT INTO category (name) VALUES ('Philosophy');

-- ===================== AUTHORS =====================
INSERT INTO author (name) VALUES ('Harper Lee');
INSERT INTO author (name) VALUES ('George Orwell');
INSERT INTO author (name) VALUES ('Jane Austen');
INSERT INTO author (name) VALUES ('F. Scott Fitzgerald');
INSERT INTO author (name) VALUES ('Herman Melville');
INSERT INTO author (name) VALUES ('Leo Tolstoy');
INSERT INTO author (name) VALUES ('Fyodor Dostoevsky');
INSERT INTO author (name) VALUES ('J.D. Salinger');
INSERT INTO author (name) VALUES ('Aldous Huxley');
INSERT INTO author (name) VALUES ('Mark Twain');
INSERT INTO author (name) VALUES ('Frank Herbert');
INSERT INTO author (name) VALUES ('Isaac Asimov');
INSERT INTO author (name) VALUES ('William Gibson');
INSERT INTO author (name) VALUES ('Ursula K. Le Guin');
INSERT INTO author (name) VALUES ('Orson Scott Card');
INSERT INTO author (name) VALUES ('Douglas Adams');
INSERT INTO author (name) VALUES ('Ray Bradbury');
INSERT INTO author (name) VALUES ('Neal Stephenson');
INSERT INTO author (name) VALUES ('Andy Weir');
INSERT INTO author (name) VALUES ('Dan Simmons');
INSERT INTO author (name) VALUES ('J.R.R. Tolkien');
INSERT INTO author (name) VALUES ('Patrick Rothfuss');
INSERT INTO author (name) VALUES ('George R.R. Martin');
INSERT INTO author (name) VALUES ('J.K. Rowling');
INSERT INTO author (name) VALUES ('Brandon Sanderson');
INSERT INTO author (name) VALUES ('C.S. Lewis');
INSERT INTO author (name) VALUES ('Christopher Paolini');
INSERT INTO author (name) VALUES ('Robert Jordan');
INSERT INTO author (name) VALUES ('Neil Gaiman');
INSERT INTO author (name) VALUES ('Stieg Larsson');
INSERT INTO author (name) VALUES ('Gillian Flynn');
INSERT INTO author (name) VALUES ('Agatha Christie');
INSERT INTO author (name) VALUES ('Dan Brown');
INSERT INTO author (name) VALUES ('Arthur Conan Doyle');
INSERT INTO author (name) VALUES ('Alex Michaelides');
INSERT INTO author (name) VALUES ('Tana French');
INSERT INTO author (name) VALUES ('Paula Hawkins');
INSERT INTO author (name) VALUES ('Liane Moriarty');
INSERT INTO author (name) VALUES ('Robert Galbraith');
INSERT INTO author (name) VALUES ('Nicholas Sparks');
INSERT INTO author (name) VALUES ('Diana Gabaldon');
INSERT INTO author (name) VALUES ('Jojo Moyes');
INSERT INTO author (name) VALUES ('John Green');
INSERT INTO author (name) VALUES ('Colleen Hoover');
INSERT INTO author (name) VALUES ('Stephenie Meyer');
INSERT INTO author (name) VALUES ('Emily Henry');
INSERT INTO author (name) VALUES ('Audrey Niffenegger');
INSERT INTO author (name) VALUES ('Julia Quinn');
INSERT INTO author (name) VALUES ('Charlotte Bronte');
INSERT INTO author (name) VALUES ('Yuval Noah Harari');
INSERT INTO author (name) VALUES ('Jared Diamond');
INSERT INTO author (name) VALUES ('Barbara Tuchman');
INSERT INTO author (name) VALUES ('Howard Zinn');
INSERT INTO author (name) VALUES ('David McCullough');
INSERT INTO author (name) VALUES ('William L. Shirer');
INSERT INTO author (name) VALUES ('Mary Beard');
INSERT INTO author (name) VALUES ('Peter Frankopan');
INSERT INTO author (name) VALUES ('Doris Kearns Goodwin');
INSERT INTO author (name) VALUES ('Jack Weatherford');
INSERT INTO author (name) VALUES ('Walter Isaacson');
INSERT INTO author (name) VALUES ('Anne Frank');
INSERT INTO author (name) VALUES ('Nelson Mandela');
INSERT INTO author (name) VALUES ('Michelle Obama');
INSERT INTO author (name) VALUES ('Ron Chernow');
INSERT INTO author (name) VALUES ('Laura Hillenbrand');
INSERT INTO author (name) VALUES ('James Clear');
INSERT INTO author (name) VALUES ('Stephen Covey');
INSERT INTO author (name) VALUES ('Dale Carnegie');
INSERT INTO author (name) VALUES ('Napoleon Hill');
INSERT INTO author (name) VALUES ('Eckhart Tolle');
INSERT INTO author (name) VALUES ('Viktor Frankl');
INSERT INTO author (name) VALUES ('Mark Manson');
INSERT INTO author (name) VALUES ('Brene Brown');
INSERT INTO author (name) VALUES ('Timothy Ferriss');
INSERT INTO author (name) VALUES ('Angela Duckworth');
INSERT INTO author (name) VALUES ('Stephen Hawking');
INSERT INTO author (name) VALUES ('Carl Sagan');
INSERT INTO author (name) VALUES ('Richard Dawkins');
INSERT INTO author (name) VALUES ('Charles Darwin');
INSERT INTO author (name) VALUES ('Rachel Carson');
INSERT INTO author (name) VALUES ('Siddhartha Mukherjee');
INSERT INTO author (name) VALUES ('Neil deGrasse Tyson');
INSERT INTO author (name) VALUES ('Daniel Kahneman');
INSERT INTO author (name) VALUES ('Thomas Kuhn');
INSERT INTO author (name) VALUES ('Marcus Aurelius');
INSERT INTO author (name) VALUES ('Plato');
INSERT INTO author (name) VALUES ('Friedrich Nietzsche');
INSERT INTO author (name) VALUES ('Martin Heidegger');
INSERT INTO author (name) VALUES ('Niccolo Machiavelli');
INSERT INTO author (name) VALUES ('Aristotle');
INSERT INTO author (name) VALUES ('Immanuel Kant');
INSERT INTO author (name) VALUES ('Jean-Paul Sartre');
INSERT INTO author (name) VALUES ('Albert Camus');

-- ===================== BOOKS =====================
-- image_url uses picsum.photos deterministic seeded images (real, working image links)
-- so every book has a distinct, guaranteed-to-load cover image for testing.
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'To Kill a Mockingbird', 'https://picsum.photos/seed/to-kill-a-mockingbird/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'Harper Lee';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT '1984', 'https://picsum.photos/seed/1984/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'George Orwell';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Pride and Prejudice', 'https://picsum.photos/seed/pride-and-prejudice/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'Jane Austen';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Great Gatsby', 'https://picsum.photos/seed/the-great-gatsby/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'F. Scott Fitzgerald';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Moby-Dick', 'https://picsum.photos/seed/moby-dick/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'Herman Melville';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'War and Peace', 'https://picsum.photos/seed/war-and-peace/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'Leo Tolstoy';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Crime and Punishment', 'https://picsum.photos/seed/crime-and-punishment/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'Fyodor Dostoevsky';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Catcher in the Rye', 'https://picsum.photos/seed/the-catcher-in-the-rye/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'J.D. Salinger';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Brave New World', 'https://picsum.photos/seed/brave-new-world/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'Aldous Huxley';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Adventures of Huckleberry Finn', 'https://picsum.photos/seed/the-adventures-of-huckleberry-finn/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Fiction' AND a.name = 'Mark Twain';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Dune', 'https://picsum.photos/seed/dune/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Frank Herbert';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Foundation', 'https://picsum.photos/seed/foundation/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Isaac Asimov';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Neuromancer', 'https://picsum.photos/seed/neuromancer/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'William Gibson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Left Hand of Darkness', 'https://picsum.photos/seed/the-left-hand-of-darkness/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Ursula K. Le Guin';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Ender''s Game', 'https://picsum.photos/seed/ender-s-game/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Orson Scott Card';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Hitchhiker''s Guide to the Galaxy', 'https://picsum.photos/seed/the-hitchhiker-s-guide-to-the-galaxy/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Douglas Adams';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Fahrenheit 451', 'https://picsum.photos/seed/fahrenheit-451/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Ray Bradbury';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Snow Crash', 'https://picsum.photos/seed/snow-crash/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Neal Stephenson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Martian', 'https://picsum.photos/seed/the-martian/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Andy Weir';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Hyperion', 'https://picsum.photos/seed/hyperion/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Science Fiction' AND a.name = 'Dan Simmons';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Hobbit', 'https://picsum.photos/seed/the-hobbit/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'J.R.R. Tolkien';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Name of the Wind', 'https://picsum.photos/seed/the-name-of-the-wind/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'Patrick Rothfuss';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'A Game of Thrones', 'https://picsum.photos/seed/a-game-of-thrones/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'George R.R. Martin';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Harry Potter and the Sorcerer''s Stone', 'https://picsum.photos/seed/harry-potter-and-the-sorcerer-s-stone/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'J.K. Rowling';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Way of Kings', 'https://picsum.photos/seed/the-way-of-kings/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'Brandon Sanderson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Mistborn: The Final Empire', 'https://picsum.photos/seed/mistborn-the-final-empire/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'Brandon Sanderson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Lion, the Witch and the Wardrobe', 'https://picsum.photos/seed/the-lion-the-witch-and-the-wardrobe/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'C.S. Lewis';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Eragon', 'https://picsum.photos/seed/eragon/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'Christopher Paolini';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Eye of the World', 'https://picsum.photos/seed/the-eye-of-the-world/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'Robert Jordan';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Good Omens', 'https://picsum.photos/seed/good-omens/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Fantasy' AND a.name = 'Neil Gaiman';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Girl with the Dragon Tattoo', 'https://picsum.photos/seed/the-girl-with-the-dragon-tattoo/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Stieg Larsson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Gone Girl', 'https://picsum.photos/seed/gone-girl/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Gillian Flynn';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'And Then There Were None', 'https://picsum.photos/seed/and-then-there-were-none/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Agatha Christie';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Da Vinci Code', 'https://picsum.photos/seed/the-da-vinci-code/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Dan Brown';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'A Study in Scarlet', 'https://picsum.photos/seed/a-study-in-scarlet/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Arthur Conan Doyle';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Silent Patient', 'https://picsum.photos/seed/the-silent-patient/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Alex Michaelides';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'In the Woods', 'https://picsum.photos/seed/in-the-woods/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Tana French';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Girl on the Train', 'https://picsum.photos/seed/the-girl-on-the-train/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Paula Hawkins';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Big Little Lies', 'https://picsum.photos/seed/big-little-lies/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Liane Moriarty';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Cuckoo''s Calling', 'https://picsum.photos/seed/the-cuckoo-s-calling/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Mystery' AND a.name = 'Robert Galbraith';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Notebook', 'https://picsum.photos/seed/the-notebook/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Nicholas Sparks';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Outlander', 'https://picsum.photos/seed/outlander/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Diana Gabaldon';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Me Before You', 'https://picsum.photos/seed/me-before-you/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Jojo Moyes';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Fault in Our Stars', 'https://picsum.photos/seed/the-fault-in-our-stars/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'John Green';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'It Ends with Us', 'https://picsum.photos/seed/it-ends-with-us/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Colleen Hoover';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Twilight', 'https://picsum.photos/seed/twilight/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Stephenie Meyer';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Beach Read', 'https://picsum.photos/seed/beach-read/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Emily Henry';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Time Traveler''s Wife', 'https://picsum.photos/seed/the-time-traveler-s-wife/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Audrey Niffenegger';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Duke and I', 'https://picsum.photos/seed/the-duke-and-i/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Julia Quinn';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Jane Eyre', 'https://picsum.photos/seed/jane-eyre/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Romance' AND a.name = 'Charlotte Bronte';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Sapiens: A Brief History of Humankind', 'https://picsum.photos/seed/sapiens-a-brief-history-of-humankind/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Yuval Noah Harari';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Guns, Germs, and Steel', 'https://picsum.photos/seed/guns-germs-and-steel/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Jared Diamond';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Guns of August', 'https://picsum.photos/seed/the-guns-of-august/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Barbara Tuchman';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'A People''s History of the United States', 'https://picsum.photos/seed/a-people-s-history-of-the-united-states/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Howard Zinn';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT '1776', 'https://picsum.photos/seed/1776/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'History' AND a.name = 'David McCullough';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Rise and Fall of the Third Reich', 'https://picsum.photos/seed/the-rise-and-fall-of-the-third-reich/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'History' AND a.name = 'William L. Shirer';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'SPQR: A History of Ancient Rome', 'https://picsum.photos/seed/spqr-a-history-of-ancient-rome/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Mary Beard';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Silk Roads', 'https://picsum.photos/seed/the-silk-roads/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Peter Frankopan';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Team of Rivals', 'https://picsum.photos/seed/team-of-rivals/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Doris Kearns Goodwin';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Genghis Khan and the Making of the Modern World', 'https://picsum.photos/seed/genghis-khan-and-the-making-of-the-modern-world/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'History' AND a.name = 'Jack Weatherford';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Steve Jobs', 'https://picsum.photos/seed/steve-jobs/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Walter Isaacson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Einstein: His Life and Universe', 'https://picsum.photos/seed/einstein-his-life-and-universe/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Walter Isaacson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Diary of a Young Girl', 'https://picsum.photos/seed/the-diary-of-a-young-girl/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Anne Frank';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Long Walk to Freedom', 'https://picsum.photos/seed/long-walk-to-freedom/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Nelson Mandela';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Becoming', 'https://picsum.photos/seed/becoming/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Michelle Obama';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Elon Musk', 'https://picsum.photos/seed/elon-musk/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Walter Isaacson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Alexander Hamilton', 'https://picsum.photos/seed/alexander-hamilton/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Ron Chernow';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Wright Brothers', 'https://picsum.photos/seed/the-wright-brothers/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'David McCullough';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Unbroken', 'https://picsum.photos/seed/unbroken/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Laura Hillenbrand';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Leonardo da Vinci', 'https://picsum.photos/seed/leonardo-da-vinci/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Biography' AND a.name = 'Walter Isaacson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Atomic Habits', 'https://picsum.photos/seed/atomic-habits/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'James Clear';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The 7 Habits of Highly Effective People', 'https://picsum.photos/seed/the-7-habits-of-highly-effective-people/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Stephen Covey';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'How to Win Friends and Influence People', 'https://picsum.photos/seed/how-to-win-friends-and-influence-people/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Dale Carnegie';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Think and Grow Rich', 'https://picsum.photos/seed/think-and-grow-rich/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Napoleon Hill';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Power of Now', 'https://picsum.photos/seed/the-power-of-now/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Eckhart Tolle';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Man''s Search for Meaning', 'https://picsum.photos/seed/man-s-search-for-meaning/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Viktor Frankl';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Subtle Art of Not Giving a F*ck', 'https://picsum.photos/seed/the-subtle-art-of-not-giving-a-f-ck/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Mark Manson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Daring Greatly', 'https://picsum.photos/seed/daring-greatly/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Brene Brown';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The 4-Hour Workweek', 'https://picsum.photos/seed/the-4-hour-workweek/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Timothy Ferriss';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Grit', 'https://picsum.photos/seed/grit/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Self-Help' AND a.name = 'Angela Duckworth';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'A Brief History of Time', 'https://picsum.photos/seed/a-brief-history-of-time/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Stephen Hawking';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Cosmos', 'https://picsum.photos/seed/cosmos/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Carl Sagan';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Selfish Gene', 'https://picsum.photos/seed/the-selfish-gene/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Richard Dawkins';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Origin of Species', 'https://picsum.photos/seed/the-origin-of-species/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Charles Darwin';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Silent Spring', 'https://picsum.photos/seed/silent-spring/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Rachel Carson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Emperor of All Maladies', 'https://picsum.photos/seed/the-emperor-of-all-maladies/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Siddhartha Mukherjee';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Astrophysics for People in a Hurry', 'https://picsum.photos/seed/astrophysics-for-people-in-a-hurry/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Neil deGrasse Tyson';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Gene: An Intimate History', 'https://picsum.photos/seed/the-gene-an-intimate-history/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Siddhartha Mukherjee';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Thinking, Fast and Slow', 'https://picsum.photos/seed/thinking-fast-and-slow/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Daniel Kahneman';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Structure of Scientific Revolutions', 'https://picsum.photos/seed/the-structure-of-scientific-revolutions/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Science' AND a.name = 'Thomas Kuhn';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Meditations', 'https://picsum.photos/seed/meditations/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Marcus Aurelius';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Republic', 'https://picsum.photos/seed/the-republic/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Plato';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Beyond Good and Evil', 'https://picsum.photos/seed/beyond-good-and-evil/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Friedrich Nietzsche';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Thus Spoke Zarathustra', 'https://picsum.photos/seed/thus-spoke-zarathustra/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Friedrich Nietzsche';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Being and Time', 'https://picsum.photos/seed/being-and-time/400/600', c.id, a.id, 9, 8 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Martin Heidegger';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Prince', 'https://picsum.photos/seed/the-prince/400/600', c.id, a.id, 10, 8 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Niccolo Machiavelli';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Nicomachean Ethics', 'https://picsum.photos/seed/nicomachean-ethics/400/600', c.id, a.id, 5, 5 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Aristotle';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Critique of Pure Reason', 'https://picsum.photos/seed/critique-of-pure-reason/400/600', c.id, a.id, 6, 5 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Immanuel Kant';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'Existentialism Is a Humanism', 'https://picsum.photos/seed/existentialism-is-a-humanism/400/600', c.id, a.id, 7, 5 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Jean-Paul Sartre';
INSERT INTO book (book_name, image_url, category_id, author_id, total_copies, available_copies) SELECT 'The Stranger', 'https://picsum.photos/seed/the-stranger/400/600', c.id, a.id, 8, 8 FROM category c, author a WHERE c.name = 'Philosophy' AND a.name = 'Albert Camus';

-- ===================== USERS =====================
INSERT INTO user (name, email, mobile_number, password, role) VALUES ('Admin User', 'admin@library.com', '9876543210', '$2a$10$mC195CHB6AaQ/R6N1mPnJO5Qd66r6uNvZ9Z8XQ/2pW7gH5jR5vP7K', 'ADMIN');
INSERT INTO user (name, email, mobile_number, password, role) VALUES ('Member User', 'member@library.com', '9876543210', '$2a$10$mC195CHB6AaQ/R6N1mPnJO5Qd66r6uNvZ9Z8XQ/2pW7gH5jR5vP7K', 'MEMBER');